simulation:
  dt: 0.01
  num_main_iters: 300
  num_sub_iters: 1

  target_object: C3
  object_random_pose_range: 0.1
  max_num_stable_pose: 50

  camera:
    phoxi:
      fx: 525.0
      fy: 525.0
      cx: 320.0
      cy: 240.0

    primesense:
      fx: 552.5
      fy: 552.5
      cx: 258.0
      cy: 193.0

policy:
  type: cross_entropy

  posterior:
    prior_strength: 5.0
    cosine_similarity_threshold: 0.95
    buffer_size: inf
    feature_dim: 128

  cross_entropy:
    num_seed_samples: 128
    num_gmm_samples: 64
    num_iters: 3
    gmm_refit_p: 0.25
    gmm_component_frac: 0.4
    gmm_reg_covar: 0.01

  cross_entorpy_posterior:
    test2: 2

sampling:
  # antipodality
  max_gripper_width: 0.08  # TODO: need camera matrix
  depth_laplacian_threshold: 0.04
  antipodal_threshold_angle: 10
  max_num_sample: 1000

  # depth
  num_depth_sample: 5
  depth_offset_min: 0.015
  depth_offset_max: 0.05
